server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /admin {
    return 301 /app/;
  }

  location /admin/ {
    return 301 /app/;
  }

  location = /app {
    return 301 /app/;
  }

  location /app/ {
    try_files $uri $uri/ /app/index.html;
  }

  location / {
    return 302 /app/;
  }
}
